name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:dev
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: |
        dpkg --add-architecture arm64
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt -o Dpkg::Options::="--force-overwrite" install -y \
          desktop-file-utils \
          gnome-pkg-tools \
          gnome-settings-daemon-dev \
          gtk-doc-tools \
          libaccountsservice-dev \
          libcolord-gtk4-dev \
          libcups2-dev \
          libgcr-4-dev \
          libgirepository1.0-dev \
          libgnome-bg-4-dev \
          libgnome-bluetooth-ui-3.0-dev \
          libgnome-rr-4-dev \
          libgnutls28-dev \
          libgoa-backend-1.0-dev \
          libgsound-dev \
          libgtop2-dev \
          libhandy-1-dev \
          libibus-1.0-dev \
          libjson-glib-dev \
          libmalcontent-0-dev \
          libmm-glib-dev \
          libnma-gtk4-dev \
          libpulse-dev \
          libpwquality-dev \
          libsecret-1-dev \
          libsmbclient-dev \
          libsoup-3.0-dev \
          libudisks2-dev \
          libupower-glib-dev \
          libwacom-dev \
          libxklavier-dev \
          libxml2-utils \
          locales \
          meson \
          python3-dbusmock \
          tecla \
          xvfb \
          blueprint-compiler \
          crossbuild-essential-arm64 \
          libcolord-gtk4-dev:arm64 \
          libcups2-dev:arm64 \
          libgcr-4-dev:arm64 \
          libgnome-bg-4-dev:arm64 \
          libgnome-bluetooth-ui-3.0-dev:arm64 \
          libgnome-rr-4-dev:arm64 \
          libgnutls28-dev:arm64 \
          libgoa-backend-1.0-dev:arm64 \
          libgsound-dev:arm64 \
          libgtop2-dev:arm64 \
          libibus-1.0-dev:arm64 \
          libjson-glib-dev:arm64 \
          libmalcontent-0-dev:arm64 \
          libnma-gtk4-dev:arm64 \
          libpulse-dev:arm64 \
          libpwquality-dev:arm64 \
          libsecret-1-dev:arm64 \
          libsmbclient-dev:arm64 \
          libsoup-3.0-dev:arm64 \
          libudisks2-dev:arm64 \
          libwacom-dev:arm64 \
          libxklavier-dev:arm64

    - name: Build debian package
      run: |
        wget https://github.com/vanilla-os/gnome-control-center/tarball/main
        mv main ../gnome-control-center_49.1.1~99-orchid-stable.orig.tar.gz
        dpkg-buildpackage -b -uc -us
        apt install -y \
          libaccountsservice-dev:arm64 \
          libhandy-1-dev:arm64 \
          libmm-glib-dev:arm64 \
          libupower-glib-dev:arm64
        dpkg-buildpackage -a arm64 -B -d -uc -us
        tar cvf ../gnome-control-center.tar.xz ../*.deb
    
    - name: Calculate and Save Checksums
      run: sha256sum /__w/gnome-control-center/gnome-control-center.tar.xz >> checksums.txt

    - uses: actions/upload-artifact@v4
      with:
        name: gnome-control-center
        path: |
            checksums.txt
            /__w/gnome-control-center/gnome-control-center.tar.xz

    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          /__w/gnome-control-center/gnome-control-center.tar.xz
          checksums.txt
